"""add meta_data to problem_records

Revision ID: 4cd0cfd4d601
Revises: a663ab129f0c
Create Date: 2026-05-11 14:35:19.614391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd0cfd4d601'
down_revision: Union[str, Sequence[str], None] = 'a663ab129f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_records', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_records', 'meta_data')
    # ### end Alembic commands ###
