"""add followup_count to sessions

Revision ID: 5af4fb1cad52
Revises: 4cd0cfd4d601
Create Date: 2026-05-11 14:38:21.688150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af4fb1cad52'
down_revision: Union[str, Sequence[str], None] = '4cd0cfd4d601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('followup_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'followup_count')
    # ### end Alembic commands ###
